import Head from 'next/head'
import React from 'react'
import MyNfticksScreen from '../frontend/components/screens/MyNfticksScreen'

function mynfticks() {
    return (
        <>
            <Head>
                <title>Check You List Of NFTicks</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MyNfticksScreen />
        </>
    )
}

export default mynfticks